substitutions:
  _GCS_BUCKET_NAME: "growmate-plant-pictures"

availableSecrets:
  secretManager:
    - versionName: projects/warm-rock-458712-a1/secrets/GCS_BACKEND_KEY/versions/latest
      env: GCS_CREDENTIALS

steps:
  # Build the WebAPI service
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/${PROJECT_ID}/webapi:${COMMIT_SHA}"
      - "-f"
      - "backend/code/Server/WebAPI/Dockerfile"
      - "backend/code"
    id: "Build WebAPI"
  
  # Build the Receiver service
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/${PROJECT_ID}/receiver:${COMMIT_SHA}"
      - "-f"
      - "backend/code/Server/ReceiverService/Dockerfile"
      - "backend/code"
    id: "Build Receiver"

  # Build the mqtt broker service
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/${PROJECT_ID}/mqtt:${COMMIT_SHA}"
      - "-f"
      - "mqtt/Dockerfile"
      - "mqtt"
    id: "Build mqtt broker"

  # Push the WebAPI image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${PROJECT_ID}/webapi:${COMMIT_SHA}"]
    waitFor: ["Build WebAPI"]
    id: "Push WebAPI"

  # Push the Receiver image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${PROJECT_ID}/receiver:${COMMIT_SHA}"]
    waitFor: ["Build Receiver"]
    id: "Push Receiver"

  # Push the mqtt broker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${PROJECT_ID}/mqtt:${COMMIT_SHA}"]
    waitFor: ["Build mqtt broker"]
    id: "Push mqtt broker"

  # Deploy mqtt broker
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "mqtt-broker"
      - "--image=gcr.io/${PROJECT_ID}/mqtt:${COMMIT_SHA}"
      - "--region=europe-north2"
      - "--platform=managed"
      - "--port=1883"
      - "--allow-unauthenticated"
      - "--project=${PROJECT_ID}"
    waitFor: ["Push mqtt broker"]
    id: "Deploy mqtt"

  # Deploy WebAPI
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "webapi-service"
      - "--image=gcr.io/${PROJECT_ID}/webapi:${COMMIT_SHA}"
      - "--region=europe-north2"
      - "--platform=managed"
      - "--port=8080"
      - "--allow-unauthenticated"
      - "--project=${PROJECT_ID}"
      - "--set-env-vars=GCS_BUCKET_NAME=${_GCS_BUCKET_NAME}"
    secretEnv: ["GCS_CREDENTIALS"]
    waitFor: ["Push WebAPI"]
    id: "Deploy WebAPI"

  # Deploy Receiver
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "receiver-service"
      - "--image=gcr.io/${PROJECT_ID}/receiver:${COMMIT_SHA}"
      - "--region=europe-north2"
      - "--platform=managed"
      - "--allow-unauthenticated"
      - "--project=${PROJECT_ID}"
    waitFor: ["Push Receiver"]
    id: "Deploy Receiver"

images:
  - "gcr.io/${PROJECT_ID}/webapi:${COMMIT_SHA}"
  - "gcr.io/${PROJECT_ID}/receiver:${COMMIT_SHA}"
  - "gcr.io/${PROJECT_ID}/mqtt:${COMMIT_SHA}"

options:
  logging: CLOUD_LOGGING_ONLY
