# cloudbuild.yaml (Example)
steps:
  # Build the WebAPI service
  - name: 'gcr.io/cloud-builders/docker'
    args: [
            'build',
            '-t', 'gcr.io/${PROJECT_ID}/webapi:${COMMIT_SHA}', # Replace with your desired image tag
            '-f', 'backend/code/Server/WebAPI/Dockerfile', # Correct Dockerfile path
            'backend/code'  # Correct build context directory
          ]
    id: 'Build WebAPI'

  # Build the Receiver service (if needed)
  - name: 'gcr.io/cloud-builders/docker'
    args: [
            'build',
            '-t', 'gcr.io/${PROJECT_ID}/receiver:${COMMIT_SHA}', # Replace with your desired image tag
            '-f', 'backend/code/Server/ReceiverService/Dockerfile', # Correct Dockerfile path
            'backend/code'  # Correct build context directory
          ]
    id: 'Build Receiver'

  - name: 'gcr.io/cloud-builders/docker'
    args: [
            'build',
            '-t', 'gcr.io/${PROJECT_ID}/mqtt:latest', # Replace with your desired image tag
            '-f', 'mqtt/Dockerfile', # Correct Dockerfile path
          ]
    id: 'Build mqtt broker'

# Add other steps like pushing the images, deploying, etc.
# ...

# List the images to be pushed to Google Container Registry
images:
  - 'gcr.io/${PROJECT_ID}/webapi:${COMMIT_SHA}'
  - 'gcr.io/${PROJECT_ID}/receiver:${COMMIT_SHA}'
  - 'gcr.io/${PROJECT_ID}/mqtt:latest'

options:
  logging: CLOUD_LOGGING_ONLY # Optional: Set logging options
