services:
  webapi:
    image: webapi
    build:
      context: .
      dockerfile: Server/WebAPI/Dockerfile
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      mqtt:
        condition: service_healthy
    restart: unless-stopped

  mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - "${MQTT_BROKER_PORT}:1883"
    volumes:
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    healthcheck:
      test:
        [
          "CMD",
          "mosquitto_pub",
          "-h",
          "localhost",
          "-t",
          "healthcheck",
          "-m",
          "ping",
          "-q",
          "1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  receiver:
    build:
      context: .
      dockerfile: Server/ReceiverService/Dockerfile
    env_file: .env
    depends_on:
      mqtt:
        condition: service_healthy
    environment:
      - MQTT_BROKER_HOST=mqtt
    restart: unless-stopped

  # sender:
  #   build:
  #     context: .
  #     dockerfile: Server/SenderService/Dockerfile
  #   env_file: .env
  #   depends_on:
  #     mqtt:
  #       condition: service_healthy
  #   environment:
  #     - MQTT_BROKER_HOST=mqtt
  #   restart: unless-stopped

volumes:
  mosquitto-data:
  mosquitto-log:
