version: "3.8"

services:
  receiver-service:
    build:
      context: ../../
      dockerfile: Server/ReceiverService/Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=35.228.249.205;Port=5432;Database=GrowMate;Username=postgres;Password=postgres;SearchPath=GrowMate
      - MqttSettings__Server=34.27.128.90
      - MqttSettings__Port=1883
      - CloudWebApiEndpoint=https://webapi-service-68779328892.europe-north2.run.app/notification/trigger
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 15s
    restart: always
