# db/Dockerfile

#FROM postgres:16

# Setting user credentials and database name
#ENV POSTGRES_USER=postgres
#ENV POSTGRES_PASSWORD=1234
#ENV POSTGRES_DB=GrowMate
#ENV POSTGRES_HOST=growmate-db

# Copying the SQL script to the Docker entrypoint initialization directory
#COPY database.sql /docker-entrypoint-initdb.d/
