name: Auto Fail
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  myjob:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a one-line script and fail
        run: exit 1
        continue-on-error: true
