name: Trigger Cloud Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  trigger-cloud-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Trigger Cloud Build
        run: |
          gcloud builds submit --config=cloudbuild.yaml --substitutions=COMMIT_SHA=${{ github.sha }}

      - name: Run container with GCS key
        run: |
          docker run --rm \
            -e GCS_BACKEND_KEY='${{ secrets.GCS_BACKEND_KEY }}'
            