name: Validate Cloud Build

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  validate-cloudbuild:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Validate Cloud Build configuration
        run: |
          # Validate the Cloud Build configuration by doing a dry run
          gcloud builds submit --config=cloudbuild.yaml --no-source --substitutions=COMMIT_SHA=${{ github.sha }}

          echo "Cloud Build configuration validated successfully!"
