name: Upload Image to Google Cloud Storage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  upload-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Authenticate with Google Cloud using the secret (this works for all collaborators who have access to the repository)
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0.5.0
        with:
          credentials_json: ${{ secrets.GCP_IMAGE_KEY_JSON }}

      